### ISSUE TITLE
CONTRIBUTING requests copyright *assignment*, not merely a CLA

### ISSUE THREAD

**Issue by edef1c** [ProtonMail/go-crypto#108]
This seems a little strange for a fork of code from the Go project, and somewhat offputting for contributing bugfixes.

**Comment by twiss** [comment]
Hey :wave: I assume you're referring to https://github.com/ProtonMail/.github/blob/main/CONTRIBUTING.md. It was written with the ProtonMail apps in mind, I agree it doesn't make as much sense for this library. I'll see if I can get that changed.

**Comment by twiss** [comment]
I've modified the clause in https://github.com/ProtonMail/go-crypto/commit/1fde58898e96d4f9850d6948ed61091e8580108e.
