### ISSUE TITLE
Support crypto.Signer for signature generation

### ISSUE THREAD

**Issue by rolandshoemaker** [ProtonMail/go-crypto#226]
The documentation for `packet.PrivateKey` says the `PrivateKey` field may be:

```
// An *{rsa|dsa|elgamal|ecdh|ecdsa|ed25519}.PrivateKey or
// crypto.Signer/crypto.Decrypter (Decryptor RSA only).
```

But this is only really true for a PubKeyAlgoRSA type keys as of 6fef34b03b21e14c4dda47f3f8e5f9e3630a70ee (#111), which removed support for using a crypto.Signer for PubKeyAlgoECDSA.

Ideally all of the key types should support a crypto.Signer, so that keys which are not stored locally can be used to generate signatures. This is currently not possible.

Would there be any objection adding this support back for ECDSA (and possibly expanding the support for all of the key types)? Based on my reading, it should be relatively trivial to implement.

**Comment by twiss** [comment]
Yeah, it was a bit of an oversight that #111 was a breaking change. So this sounds reasonable to me :+1:
