### ISSUE TITLE
Encode and EncodeWithHeader look the same

### ISSUE THREAD

**Issue by mdosch** [ProtonMail/go-crypto#239]
Dear ProtonMail team,

it seems [Encode](https://pkg.go.dev/github.com/ProtonMail/go-crypto@v1.1.0/openpgp/clearsign#Encode) and [EncodeWhithHeader](https://pkg.go.dev/github.com/ProtonMail/go-crypto@v1.1.0/openpgp/clearsign#EncodeWithHeader) expect both a headers map while only the latter should.

This is probably the cause of https://github.com/sylabs/sif/issues/388.

**Comment by rykov** [comment]
I've encountered this too, and changes to `.Encode` seem to have been made by mistake because it breaks backward compatibility without a major version change.

**Comment by lubux** [comment]
Hi. Thanks for the report. This is indeed an oversight. We can merge the fix today and I will make another release.

**Comment by lubux** [comment]
https://github.com/ProtonMail/go-crypto/releases/tag/v1.1.1

**Comment by rykov** [comment]
@lubux Thank you for the quick turnaround!
