### ISSUE TITLE
Missing FlagAuthenticate in packet.Signature

### ISSUE THREAD

**Issue by phiekl** [ProtonMail/go-crypto#93]
I expected to find FlagAuthenticate in https://github.com/ProtonMail/go-crypto/blob/a4f6767435ab/openpgp/packet/signature.go#L34 since that's part of the spec as 0x20: https://www.rfc-editor.org/rfc/rfc4880.html#section-5.2.3.21

There's a patch created by @chaosaffe that fixes this, and it applies to your code base without issues. It can be found at https://go-review.googlesource.com/c/crypto/+/120315 and it was discussed in https://github.com/golang/go/issues/25983.

Any chance you could add this? (I was about to create a pull request, but seeing your Contribution Policy, I didn't.)

**Comment by chaosaffe** [comment]
I'm not sure who the _you_ in this context is, but I shall assume it is the maintainers of ProtonMail/go-crypto. I am happy to offer my patch to this package, either through a direct contribution, or by authorising any use of my patch to golang/go.

If there is anything I can do to facilitate this patch please let me know

**Comment by twiss** [comment]
Hi! Yeah, a PR would definitely be welcome :+1:

(The contribution policy of the ProtonMail org shouldn't really apply to this package, anyway, as it's a fork of x/crypto. I'll try to change that.)

**Comment by chaosaffe** [comment]
I've opened a PR with the patch from https://github.com/golang/go/issues/25983 applied to this repo. Please let me know if I can do anything to move this along!
